// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TdpTrans.Repositories;

#nullable disable

namespace TdpTrans.Repositories.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260506110712_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TdpTrans.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "contact@techlog.ro",
                            Name = "Tech Logistics SRL",
                            Phone = "0722111222"
                        },
                        new
                        {
                            Id = 2,
                            Email = "office@autodepanare.ro",
                            Name = "Auto Depanare SA",
                            Phone = "0733444555"
                        },
                        new
                        {
                            Id = 3,
                            Email = "ion.popescu@gmail.com",
                            Name = "Ion Popescu",
                            Phone = "0744999888"
                        });
                });

            modelBuilder.Entity("TdpTrans.Models.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TruckId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("TruckId");

                    b.ToTable("Missions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Strada Lunga 10, Cluj-Napoca",
                            ClientId = 1,
                            Cost = 1500.00m,
                            Date = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TruckId = 123456,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Autostrada A3, km 25",
                            ClientId = 2,
                            Cost = 450.50m,
                            Date = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TruckId = 654321,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "Bulevardul Unirii, Bucuresti",
                            ClientId = 3,
                            Cost = 3200.00m,
                            Date = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TruckId = 112233,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Address = "Soseaua Vestului, Ploiesti",
                            ClientId = 1,
                            Cost = 800.00m,
                            Date = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TruckId = 123456,
                            Type = 0
                        });
                });

            modelBuilder.Entity("TdpTrans.Models.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trucks");

                    b.HasData(
                        new
                        {
                            Id = 123456,
                            LicensePlate = "CJ 99 TEST"
                        },
                        new
                        {
                            Id = 654321,
                            LicensePlate = "B 101 DEV"
                        },
                        new
                        {
                            Id = 112233,
                            LicensePlate = "TM 50 RAP"
                        });
                });

            modelBuilder.Entity("TdpTrans.Models.Mission", b =>
                {
                    b.HasOne("TdpTrans.Models.Client", "Client")
                        .WithMany("Missions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TdpTrans.Models.Truck", "Truck")
                        .WithMany("Missions")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("TdpTrans.Models.Client", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("TdpTrans.Models.Truck", b =>
                {
                    b.Navigation("Missions");
                });
#pragma warning restore 612, 618
        }
    }
}
